
-- ===========================================
-- MySQL Version of KupiCoffee-SystemDB.sql
-- ===========================================

-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTID INT AUTO_INCREMENT PRIMARY KEY,
    C_USERNAME VARCHAR(50),
    C_PASS VARCHAR(50),
    C_PHONENUM VARCHAR(20),
    C_EMAIL VARCHAR(100),
    C_ADDRESS VARCHAR(255)
);

-- Table: STAFF
CREATE TABLE STAFF (
    STAFFID INT AUTO_INCREMENT PRIMARY KEY,
    S_USERNAME VARCHAR(50),
    S_PASS VARCHAR(50),
    S_PHONENUM VARCHAR(20),
    S_EMAIL VARCHAR(100),
    S_ROLE VARCHAR(255)
);

-- Table: KUPI
CREATE TABLE KUPI (
    KUPIID INT AUTO_INCREMENT PRIMARY KEY,
    K_NAME VARCHAR(50),
    K_PRICE DECIMAL(10,2),
    K_DESC VARCHAR(500),
    K_IMAGE LONGBLOB
);

-- Table: ORDERTABLE
CREATE TABLE ORDERTABLE (
    ORDERID INT AUTO_INCREMENT PRIMARY KEY,
    KUPIMILK VARCHAR(50),
    KUPITYPE VARCHAR(50),
    KUPISIZE VARCHAR(50),
    KUPICREAM VARCHAR(50),
    KUPIBEAN VARCHAR(50),
    KUPIDATE DATE,
    CUSTID INT,
    STAFFID INT,
    FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID),
    FOREIGN KEY (STAFFID) REFERENCES STAFF(STAFFID)
);

-- Table: ORDERDETAIL
CREATE TABLE ORDERDETAIL (
    ORDERDETAILID INT AUTO_INCREMENT PRIMARY KEY,
    QUANTITY INT,
    PRICEPERORDER DECIMAL(10,2),
    SUBTOTAL DECIMAL(10,2),
    KUPIID INT,
    ORDERID INT,
    FOREIGN KEY (KUPIID) REFERENCES KUPI(KUPIID),
    FOREIGN KEY (ORDERID) REFERENCES ORDERTABLE(ORDERID)
);

-- Table: DELIVERY
CREATE TABLE DELIVERY (
    ORDERID INT PRIMARY KEY,
    D_TIME DATE,
    D_STATUS VARCHAR(50),
    FOREIGN KEY (ORDERID) REFERENCES ORDERTABLE(ORDERID)
);

-- Table: PICKUP
CREATE TABLE PICKUP (
    ORDERID INT PRIMARY KEY,
    P_TIME DATE,
    P_STATUS VARCHAR(50),
    FOREIGN KEY (ORDERID) REFERENCES ORDERTABLE(ORDERID)
);
